<div id="custom-content">
    <label for="name">Tài Khoản</label>
    <input id="name" type="text" />

    <label for="pass">Password</label>
    <input id="pass" type="password" />

    <button type="submit">Login</button>
</div>
<div id="newpage" class="flex-container">
    <button id="btn2" class="button" >Open Magento Login modal</button>
    <button id="btn3" class="button" >Open Custom Login modal</button>
</div>
<script type="text/x-magento-init">
    {
        "#newpage": {
            "buttonClick": {}
    }
}
</script>
