<select name="custom-select" id="color_select">
    <?php $colors = $block->getColors(); ?>
    <?php if ($colors): ?>
        <option value="">color</option>
        <?php foreach ($colors as $color): ?>
            <option value="<?php echo $color['value']; ?>" style="background-color: <?php echo $color['value']; ?>;">
                <?php echo $color['color']; ?>
            </option>
        <?php endforeach; ?>
    <?php else: ?>
        <option value="">No colors available</option>
    <?php endif; ?>
</select>
<script type="text/javascript">
    require(['jquery'], function($) {
        $(document).ready(function() {
            $('#color_select').on('change', function() {
                var selectedColor = $(this).val(); // Lấy giá trị màu đã chọn
                $('.panel.wrapper').css('background-color', selectedColor); // Cập nhật màu nền cho header
            });
        });
    });
</script>
