<div class="modal-content" id="promotion-popup">
    <h2>Promotions for You!</h2>
    <table>
        <thead>
        <tr>
            <th>Customer Group</th>
            <th>Promotion</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($block->getPromotions() as $promotion): ?>
            <tr>
                <td><?php echo $promotion['customer_group_code']; ?></td>
                <td><?php echo $promotion['promotion_text']; ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>


<script type="text/javascript">
    require(['jquery','Magento_Ui/js/modal/modal'], function ($, modal) {
        $(document).ready(function () {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: '',
                buttons: []
            };
            modal(options, $('#promotion-popup'));
            // Show popup on homepage load
            if ($('body').hasClass('cms-home')) {
                $("#promotion-popup").modal("openModal");
            }
        });
    });
</script>
