<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title">NewPage</span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item total-installs">
            <div class="admin__page-section-item-title">
                <span class="title">Total Number Module</span>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary">
                        <tbody>
                        <tr>
                            <th>Number Of Module Install</th>
                            <td><?php echo $block->getInstalledModuleCount()?></td>
                        </tr>
                        <tr>
                            <th>Number Of Module Install not belong to Vendor</th>
                            <td><?php echo $block->getModuleCountFromTable()?></td>
                        </tr>
                        </tbody>
                </table>
            </div>
        </div>
        <div class="admin__page-section-item detail-info">
            <div class="admin__page-section-item-title">
                <span class="title">Detail Info</span>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary">
                    <tbody>
                    <tr>
                        <th>Number Of Customers</th>
                        <td><?php echo $block->getCustomerCount()?></td>
                    </tr>
                    <tr>
                        <th>Number Of Products</th>
                        <td><?php echo $block->getProductCount()?></td>
                    </tr>
                    <tr>
                        <th>Number Of Orders</th>
                        <td><?php echo $block->getOrderCount()?></td>
                    </tr>
                    <tr>
                        <th>Number Of Invoices</th>
                        <td><?php echo $block->getInvoiceCount()?></td>
                    </tr>
                    <tr>
                        <th>Number Of Creditmemos</th>
                        <td><?php echo $block->getCreditmemoCount()?></td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</section>
